[head_tail_cmd]
# 头部插入命令
head = """
MT 1 0 0
MT 2 0 0
MT 3 0 0
MT 5 0 0
MT 6 0 0
MT 8 0 0
ZERO 1 0
ZERO 2 0
ZERO 3 0
ZERO 4 0
ZERO 5 0
ZERO 6 0
ZERO 8 0
MDP 4 10 0
MTP 2 30000 30000 1000 8
MT 2 0 0
ZERO 2 0
POS_INIT 8 1000 -50 8.5 0.8 30
MDP 8 100  10
MDP 8 100  0
MDP 3 200 2.25
POS_INIT 6 1000 -50 8.5 0.8 30
MDP 6 100  10
MDP 6 100  0
MDP 3 200 0


DAT1 = 0
DAT2 = 0
DAT3 = 0
DAT5 = 0

DAT200 = 10
DAT201 = 20
DAT202 = 30
DAT300 = 0.4
DAT500 = 400
DAT501 = -100

DAT900 = 0
DAT901 = 30.5
DAT902 = 20.5
DAT903 = 12.5
DAT904 = 0.5

DAT620 = 11
DAT621 = 25.9
DAT622 = 37.5
DAT623 = 23.7
DAT626 = 19.5

DAT820 = 10.8
DAT821 = 25.9
DAT822 = 37.5
DAT823 = 23.5
DAT826 = 19.3

DAT910 = -4.5
DAT911 = 0
DAT912 = -1.5
DAT914 = -4
DAT915 = -6.5

DAT101 = 2.25
DAT102 = 4.50
DAT103 = 6.75
DAT104 = 9.00
DAT105 = 11.25
DAT106 = 13.50
DAT107 = 15.75

DAT_INDEX = 0
"""

# 尾部插入命令
tail = """
T 1000
"""