[luola]
0 = """
MDP 5 1000 DAT5
"""
1 = """
DAT5 += 300
MDP 5 1000 DAT5
DAT5 -= 80
MDP 5 1000 DAT5
"""
2 = """
DAT5 += 300
MDP 5 1000 DAT5
DAT5 -= 80
MDP 5 1000 DAT5
"""
3 = """
DAT5 += 300
MDP 5 1000 DAT5
DAT5 -= 80
MDP 5 1000 DAT5
"""
4 = """
DAT5 += 300
MDP 5 1000 DAT5
DAT5 -= 80
MDP 5 1000 DAT5
"""
5 = """
DAT5 += 300
MDP 5 1000 DAT5
DAT5 -= 80
MDP 5 1000 DAT5
"""
6 = """
DAT5 += 300
MDP 5 1000 DAT5
DAT5 -= 80
MDP 5 1000 DAT5
"""
7 = """
DAT5 += 300
MDP 5 1000 DAT5
DAT5 -= 80
MDP 5 1000 DAT5
"""
8 = """
DAT5 += 300
MDP 5 1000 DAT5
DAT5 -= 80
MDP 5 1000 DAT5
"""
9 = """
DAT5 += 300
MDP 5 1000 DAT5
DAT5 -= 80
MDP 5 1000 DAT5
"""
10 = """
DAT5 += 300
MDP 5 1000 DAT5
DAT5 -= 80
MDP 5 1000 DAT5
"""