[sema]
# 正向数据
"+0" = """
T 0
"""
"+1" = """
T 0
"""
"+2" = """
T 0
"""
"+3" = """
T 0
"""
"+4" = """
MDP 3 200 DAT3
T 1
IF DAT1 != 0
DAT1 = -1
MDP 1 200 DAT1
DAT1 = 0
MDP 1 200 DAT1
ENDIF
DAT2 -= 10
MTP 2 30000 30000 1000 DAT2
MDP 8 1000 DAT902

MDP 8 1000 DAT903
T 3
DAT2 += 30
MTP 2 30000 30000 1000 DAT2
MDP 8 1000 DAT910
MDP 8 1000 DAT904
DAT2 -= 20
MTP 2 30000 30000 1000 DAT2
"""
"+5" = """
MDP 3 200 DAT3
T 1
IF DAT1 != 0
DAT1 = -1
MDP 1 200 DAT1
DAT1 = 0
MDP 1 200 DAT1
ENDIF
DAT2 -= 10
MTP 2 30000 30000 1000 DAT2
MDP 6 1000 DAT902
MDP 6 1000 DAT903
T 3
DAT2 += 30
MTP 2 30000 30000 1000 DAT2
MDP 6 1000 DAT910
MDP 6 1000 DAT904
DAT2 -= 20
MTP 2 30000 30000 1000 DAT2
"""
"+8" = """
MDP 3 200 DAT3
T 1
IF DAT1 != 0
DAT1 = -1
MDP 1 200 DAT1
DAT1 = 0
MDP 1 200 DAT1
ENDIF
DAT2 -= 10
MTP 2 30000 30000 1000 DAT2
MDP 8 1000 DAT902
MDP 8 500 DAT901
MDP 8 500 DAT903
T 3
DAT2 += 30
MTP 2 30000 30000 1000 DAT2
MDP 8 1000 DAT910
MDP 8 1000 DAT904
DAT2 -= 20
MTP 2 30000 30000 1000 DAT2
"""
"+9" = """
MDP 3 200 DAT3
T 1
IF DAT1 != 0
DAT1 = -1
MDP 1 200 DAT1
DAT1 = 0
MDP 1 200 DAT1
ENDIF
DAT2 -= 10
MTP 2 30000 30000 1000 DAT2
MDP 6 1000 DAT902
MDP 6 500 DAT901
MDP 6 500 DAT903
T 3
DAT2 += 30
MTP 2 30000 30000 1000 DAT2
MDP 6 1000 DAT910
MDP 6 1000 DAT904
DAT2 -= 20
MTP 2 30000 30000 1000 DAT2
"""
"+10" = """
MDP 3 200 DAT3
T 1
IF DAT1 != 0
DAT1 = -1
MDP 1 200 DAT1
DAT1 = 0
MDP 1 200 DAT1
ENDIF
DAT2 -= 10
MTP 2 30000 30000 1000 DAT2
MDP 8 1000 DAT902
MDP 8 500 DAT901
MDP 8 500 DAT903
T 3
DAT2 += 30
MTP 2 30000 30000 1000 DAT2
MDP 8 1000 DAT910
MDP 8 1000 DAT904
DAT2 -= 30
DAT2 += 2.25
MTP 2 30000 30000 1000 DAT2
DAT3 += 2.25
MDP 3 200 DAT3
T 1
MDP 6 1000 DAT902
MDP 6 500 DAT901
MDP 6 500 DAT903
T 3
DAT2 += 30
MTP 2 30000 30000 1000 DAT2
MDP 6 1000 DAT910
MDP 6 1000 DAT904
DAT2 -= 20
DAT2 -= 2.25
DAT3 -= 2.25
MTP 2 30000 30000 1000 DAT2
MDP 3 200 DAT3
"""
"+15" = """
MDP 3 200 DAT3
T 1
IF DAT1 != 0
DAT1 = -1
MDP 1 200 DAT1
DAT1 = 0
MDP 1 200 DAT1
ENDIF
MDP 8 500 DAT901
MDP 8 500 DAT910
MDP 8 500 DAT904
"""
"+16" = """
MTP 2 30000 30000 1000 DAT2
MDP 3 200 DAT3
"""
"+17" = """
MDP 3 200 DAT3
T 1
IF DAT1 != 0
DAT1 = -1
MDP 1 200 DAT1
DAT1 = 0
MDP 1 200 DAT1
ENDIF
MDP 6 500 DAT901
MDP 6 500 DAT910
MDP 6 500 DAT904
"""
"+21" = """
MDP 3 200 DAT3
T 1
IF DAT1 != -6.75
DAT1 = -6.75
DAT1 -= 2
MDP 1 200 DAT1
DAT1 = -6.75
MDP 1 200 DAT1
ENDIF
MDP 8 1000 DAT822
MDP 8 1000 DAT821
MDP 6 1000 DAT620
T 3
MDP 8 1000 DAT823
MDP 8 1000 DAT822
MDP 6 1000 DAT626
MDP 8 1000 DAT900
MDP 8 1000 DAT904
MDP 6 1000 DAT900
MDP 6 1000 DAT904
"""
"+22" = """
MDP 3 200 DAT3
T 1
IF DAT1 != -11.25
DAT1 = -11.25
DAT1 -= 2
MDP 1 200 DAT1
DAT1 = -11.25
MDP 1 200 DAT1
ENDIF
MDP 8 1000 DAT822
MDP 8 1000 DAT821
MDP 6 1000 DAT620
T 3
MDP 8 1000 DAT823
MDP 8 1000 DAT822
MDP 6 1000 DAT626
MDP 8 1000 DAT900
MDP 8 1000 DAT904
MDP 6 1000 DAT900
MDP 6 1000 DAT904
"""
"+23" = """
MDP 3 200 DAT3
T 1
IF DAT1 != -15.75
DAT1 = -15.75
DAT1 -= 2
MDP 1 200 DAT1
DAT1 = -15.75
MDP 1 200 DAT1
ENDIF
MDP 8 1000 DAT822
MDP 8 1000 DAT821
MDP 6 1000 DAT620
T 3
MDP 8 1000 DAT823
MDP 8 1000 DAT822
MDP 6 1000 DAT626
MDP 8 1000 DAT900
MDP 8 1000 DAT904
MDP 6 1000 DAT900
MDP 6 1000 DAT904
"""
"+31" = """
MDP 3 200 DAT3
T 1
IF DAT1 != 2.25
DAT1 = 2.25
DAT1 -= 2
MDP 1 200 DAT1
DAT1 = 2.25
MDP 1 200 DAT1
ENDIF
MDP 8 1000 DAT822
MDP 8 1000 DAT821
MDP 6 1000 DAT620
T 3
MDP 8 1000 DAT823
MDP 8 1000 DAT822
MDP 6 1000 DAT626
MDP 8 1000 DAT900
MDP 8 1000 DAT904
MDP 6 1000 DAT900
MDP 6 1000 DAT904
"""
"+32" = """
MDP 3 200 DAT3
T 1
IF DAT1 != 6.75
DAT1 = 6.75
DAT1 -= 2
MDP 1 200 DAT1
DAT1 = 6.75
MDP 1 200 DAT1
ENDIF
MDP 8 1000 DAT822
MDP 8 1000 DAT821
MDP 6 1000 DAT620
T 3
MDP 8 1000 DAT823
MDP 8 1000 DAT822
MDP 6 1000 DAT626
MDP 8 1000 DAT900
MDP 8 1000 DAT904
MDP 6 1000 DAT900
MDP 6 1000 DAT904
"""
"+33" = """
MDP 3 200 DAT3
T 1
IF DAT1 != 11.25
DAT1 = 11.25
DAT1 -= 2
MDP 1 200 DAT1
DAT1 = 11.25
MDP 1 200 DAT1
ENDIF
MDP 8 1000 DAT822
MDP 8 1000 DAT821
MDP 6 1000 DAT620
T 3
MDP 8 1000 DAT823
MDP 8 1000 DAT822
MDP 6 1000 DAT626
MDP 8 1000 DAT900
MDP 8 1000 DAT904
MDP 6 1000 DAT900
MDP 6 1000 DAT904
"""
"+41" = """
MDP 3 200 DAT3
T 1
IF DAT1 != 2.25
DAT1 = 2.25
DAT1 -= 2
MDP 1 200 DAT1
DAT1 = 2.25
MDP 1 200 DAT1
ENDIF
DAT3 += 2.25
MDP 3 200 DAT3
T 1
MDP 6 1000 DAT622
MDP 6 1000 DAT621
MDP 8 1000 DAT820
T 3
MDP 6 1000 DAT623
MDP 6 1000 DAT622
MDP 8 1000 DAT826
MDP 6 1000 DAT900
MDP 6 1000 DAT904
MDP 8 1000 DAT900
MDP 8 1000 DAT904
DAT3 -= 2.25
"""
"+42" = """
MDP 3 200 DAT3
T 1
IF DAT1 != 6.75
DAT1 = 6.75
DAT1 -= 2
MDP 1 200 DAT1
DAT1 = 6.75
MDP 1 200 DAT1
ENDIF
DAT3 += 6.75
MDP 3 200 DAT3
T 1
MDP 6 1000 DAT622
MDP 6 1000 DAT621
MDP 8 1000 DAT820
T 3
MDP 6 1000 DAT623
MDP 6 1000 DAT622
MDP 8 1000 DAT826
MDP 6 1000 DAT900
MDP 6 1000 DAT904
MDP 8 1000 DAT900
MDP 8 1000 DAT904
DAT3 -= 6.75
"""
"+43" = """
MDP 3 200 DAT3
T 1
IF DAT1 != 11.25
DAT1 = 11.25
DAT1 -= 2
MDP 1 200 DAT1
DAT1 = 11.25
MDP 1 200 DAT1
ENDIF
DAT3 += 11.25
MDP 3 200 DAT3
T 1
MDP 6 1000 DAT622
MDP 6 1000 DAT621
MDP 8 1000 DAT820
T 3
MDP 6 1000 DAT623
MDP 6 1000 DAT622
MDP 8 1000 DAT826
MDP 6 1000 DAT900
MDP 6 1000 DAT904
MDP 8 1000 DAT900
MDP 8 1000 DAT904
DAT3 -= 11.25
"""
"+51" = """
MDP 3 200 DAT3
T 1
IF DAT1 != -6.75
DAT1 = -6.75
DAT1 -= 2
MDP 1 200 DAT1
DAT1 = -6.75
MDP 1 200 DAT1
ENDIF
DAT3 -= 6.75
MDP 3 200 DAT3
T 1
MDP 6 1000 DAT622
MDP 6 1000 DAT621
MDP 8 1000 DAT820
T 3
MDP 6 1000 DAT623
MDP 6 1000 DAT622
MDP 8 1000 DAT826
MDP 6 1000 DAT900
MDP 6 1000 DAT904
MDP 8 1000 DAT900
MDP 8 1000 DAT904
DAT3 += 6.75
"""
"+52" = """
MDP 3 200 DAT3
T 1
IF DAT1 != -11.25
DAT1 = -11.25
DAT1 -= 2
MDP 1 200 DAT1
DAT1 = -11.25
MDP 1 200 DAT1
ENDIF
DAT3 -= 11.25
MDP 3 200 DAT3
T 1
MDP 6 1000 DAT622
MDP 6 1000 DAT621
MDP 8 1000 DAT820
T 3
MDP 6 1000 DAT623
MDP 6 1000 DAT622
MDP 8 1000 DAT826
MDP 6 1000 DAT900
MDP 6 1000 DAT904
MDP 8 1000 DAT900
MDP 8 1000 DAT904
DAT3 += 11.25
"""
"+53" = """
MDP 3 200 DAT3
T 1
IF DAT1 != -15.75
DAT1 = -15.75
DAT1 -= 2
MDP 1 200 DAT1
DAT1 = -15.75
MDP 1 200 DAT1
ENDIF
DAT3 -= 15.75
MDP 3 200 DAT3
T 1
MDP 6 1000 DAT622
MDP 6 1000 DAT621
MDP 8 1000 DAT820
T 3
MDP 6 1000 DAT623
MDP 6 1000 DAT622
MDP 8 1000 DAT826
MDP 6 1000 DAT900
MDP 6 1000 DAT904
MDP 8 1000 DAT900
MDP 8 1000 DAT904
DAT3 += 15.75
"""
"+100" = """
MDP 3 200 DAT3
T 1
IF DAT1 != -2.25
DAT1 = -2.25
DAT1 -= 2
MDP 1 200 DAT1
DAT1 = -2.25
MDP 1 200 DAT1
ENDIF
MDP 8 1000 DAT822
MDP 8 1000 DAT821
MDP 6 1000 DAT620
T 3
MDP 8 1000 DAT823
MDP 8 1000 DAT822
MDP 6 1000 DAT626
MDP 8 1000 DAT900
MDP 8 1000 DAT904
MDP 6 1000 DAT900
MDP 6 1000 DAT904
"""
"+110" = """
MDP 3 200 DAT3
T 1
IF DAT1 != -2.25
DAT1 = -2.25
DAT1 -= 2
MDP 1 200 DAT1
DAT1 = -2.25
MDP 1 200 DAT1
ENDIF
DAT3 -= 2.25
MDP 3 200 DAT3
T 1
MDP 6 1000 DAT622
MDP 6 1000 DAT621
MDP 8 1000 DAT820
T 3
MDP 6 1000 DAT623
MDP 6 1000 DAT622
MDP 8 1000 DAT826
MDP 6 1000 DAT900
MDP 6 1000 DAT904
MDP 8 1000 DAT900
MDP 8 1000 DAT904
DAT3 += 2.25
"""

# 负向数据
"-0" = """
T 0
"""
"-1" = """
T 0
"""
"-2" = """
T 0
"""
"-3" = """
T 0
"""
"-4" = """
MDP 3 200 DAT3
T 1
IF DAT1 != 0
DAT1 = -1
MDP 1 200 DAT1
DAT1 = 0
MDP 1 200 DAT1
ENDIF
DAT2 += 10
MTP 2 30000 30000 1000 DAT2
MDP 8 1000 DAT902

MDP 8 1000 DAT903
T 3
DAT2 -= 30
MTP 2 30000 30000 1000 DAT2
MDP 8 1000 DAT910
MDP 8 1000 DAT904
DAT2 += 20
MTP 2 30000 30000 1000 DAT2
"""
"-5" = """
MDP 3 200 DAT3
T 1
IF DAT1 != 0
DAT1 = -1
MDP 1 200 DAT1
DAT1 = 0
MDP 1 200 DAT1
ENDIF
DAT2 += 10
MTP 2 30000 30000 1000 DAT2
MDP 6 1000 DAT902
MDP 6 1000 DAT903
T 3
DAT2 -= 30
MTP 2 30000 30000 1000 DAT2
MDP 6 1000 DAT910
MDP 6 1000 DAT904
DAT2 += 20
MTP 2 30000 30000 1000 DAT2
"""
"-8" = """
MDP 3 200 DAT3
T 1
IF DAT1 != 0
DAT1 = -1
MDP 1 200 DAT1
DAT1 = 0
MDP 1 200 DAT1
ENDIF
DAT2 += 10
MTP 2 30000 30000 1000 DAT2
MDP 8 1000 DAT902
MDP 8 500 DAT901
MDP 8 500 DAT903
T 3
DAT2 -= 30
MTP 2 30000 30000 1000 DAT2
MDP 8 1000 DAT910
MDP 8 1000 DAT904
DAT2 += 20
MTP 2 30000 30000 1000 DAT2
"""
"-9" = """
MDP 3 200 DAT3
T 1
IF DAT1 != 0
DAT1 = -1
MDP 1 200 DAT1
DAT1 = 0
MDP 1 200 DAT1
ENDIF
DAT2 += 10
MTP 2 30000 30000 1000 DAT2
MDP 6 1000 DAT902
MDP 6 500 DAT901
MDP 6 500 DAT903
T 3
DAT2 -= 30
MTP 2 30000 30000 1000 DAT2
MDP 6 1000 DAT910
MDP 6 1000 DAT904
DAT2 += 20
MTP 2 30000 30000 1000 DAT2
"""
"-10" = """
MDP 3 200 DAT3
T 1
IF DAT1 != 0
DAT1 = -1
MDP 1 200 DAT1
DAT1 = 0
MDP 1 200 DAT1
ENDIF
DAT2 += 10
MTP 2 30000 30000 1000 DAT2
MDP 8 1000 DAT902
MDP 8 500 DAT901
MDP 8 500 DAT903
T 3
DAT2 -= 30
MTP 2 30000 30000 1000 DAT2
MDP 8 1000 DAT910
MDP 8 1000 DAT904
DAT2 += 30
DAT2 += 2.25
MTP 2 30000 30000 1000 DAT2
DAT3 += 2.25
MDP 3 200 DAT3
T 1
MDP 6 1000 DAT902
MDP 6 500 DAT901
MDP 6 500 DAT903
T 3
DAT2 -= 30
MTP 2 30000 30000 1000 DAT2
MDP 6 1000 DAT910
MDP 6 1000 DAT904
DAT2 += 20
DAT2 -= 2.25
DAT3 -= 2.25
MTP 2 30000 30000 1000 DAT2
MDP 3 200 DAT3
"""
"-15" = """
MDP 3 200 DAT3
T 1
IF DAT1 != 0
DAT1 = -1
MDP 1 200 DAT1
DAT1 = 0
MDP 1 200 DAT1
ENDIF
MDP 8 500 DAT901
MDP 8 500 DAT910
MDP 8 500 DAT904
"""
"-16" = """
MTP 2 30000 30000 1000 DAT2
MDP 3 200 DAT3
"""
"-17" = """
MDP 3 200 DAT3
T 1
IF DAT1 != 0
DAT1 = -1
MDP 1 200 DAT1
DAT1 = 0
MDP 1 200 DAT1
ENDIF
MDP 6 500 DAT901
MDP 6 500 DAT910
MDP 6 500 DAT904
"""
"-21" = """
MDP 3 200 DAT3
T 1
IF DAT1 != -6.75
DAT1 = -6.75
DAT1 -= 2
MDP 1 200 DAT1
DAT1 = -6.75
MDP 1 200 DAT1
ENDIF
MDP 8 1000 DAT822
MDP 8 1000 DAT821
MDP 6 1000 DAT620
T 3
MDP 8 1000 DAT823
MDP 8 1000 DAT822
MDP 6 1000 DAT626
MDP 8 1000 DAT900
MDP 8 1000 DAT904
MDP 6 1000 DAT900
MDP 6 1000 DAT904
"""
"-22" = """
MDP 3 200 DAT3
T 1
IF DAT1 != -11.25
DAT1 = -11.25
DAT1 -= 2
MDP 1 200 DAT1
DAT1 = -11.25
MDP 1 200 DAT1
ENDIF
MDP 8 1000 DAT822
MDP 8 1000 DAT821
MDP 6 1000 DAT620
T 3
MDP 8 1000 DAT823
MDP 8 1000 DAT822
MDP 6 1000 DAT626
MDP 8 1000 DAT900
MDP 8 1000 DAT904
MDP 6 1000 DAT900
MDP 6 1000 DAT904
"""
"-23" = """
MDP 3 200 DAT3
T 1
IF DAT1 != -15.75
DAT1 = -15.75
DAT1 -= 2
MDP 1 200 DAT1
DAT1 = -15.75
MDP 1 200 DAT1
ENDIF
MDP 8 1000 DAT822
MDP 8 1000 DAT821
MDP 6 1000 DAT620
T 3
MDP 8 1000 DAT823
MDP 8 1000 DAT822
MDP 6 1000 DAT626
MDP 8 1000 DAT900
MDP 8 1000 DAT904
MDP 6 1000 DAT900
MDP 6 1000 DAT904
"""
"-31" = """
MDP 3 200 DAT3
T 1
IF DAT1 != 2.25
DAT1 = 2.25
DAT1 -= 2
MDP 1 200 DAT1
DAT1 = 2.25
MDP 1 200 DAT1
ENDIF
MDP 8 1000 DAT822
MDP 8 1000 DAT821
MDP 6 1000 DAT620
T 3
MDP 8 1000 DAT823
MDP 8 1000 DAT822
MDP 6 1000 DAT626
MDP 8 1000 DAT900
MDP 8 1000 DAT904
MDP 6 1000 DAT900
MDP 6 1000 DAT904
"""
"-32" = """
MDP 3 200 DAT3
T 1
IF DAT1 != 6.75
DAT1 = 6.75
DAT1 -= 2
MDP 1 200 DAT1
DAT1 = 6.75
MDP 1 200 DAT1
ENDIF
MDP 8 1000 DAT822
MDP 8 1000 DAT821
MDP 6 1000 DAT620
T 3
MDP 8 1000 DAT823
MDP 8 1000 DAT822
MDP 6 1000 DAT626
MDP 8 1000 DAT900
MDP 8 1000 DAT904
MDP 6 1000 DAT900
MDP 6 1000 DAT904
"""
"-33" = """
MDP 3 200 DAT3
T 1
IF DAT1 != 11.25
DAT1 = 11.25
DAT1 -= 2
MDP 1 200 DAT1
DAT1 = 11.25
MDP 1 200 DAT1
ENDIF
MDP 8 1000 DAT822
MDP 8 1000 DAT821
MDP 6 1000 DAT620
T 3
MDP 8 1000 DAT823
MDP 8 1000 DAT822
MDP 6 1000 DAT626
MDP 8 1000 DAT900
MDP 8 1000 DAT904
MDP 6 1000 DAT900
MDP 6 1000 DAT904
"""
"-41" = """
MDP 3 200 DAT3
T 1
IF DAT1 != 2.25
DAT1 = 2.25
DAT1 -= 2
MDP 1 200 DAT1
DAT1 = 2.25
MDP 1 200 DAT1
ENDIF
DAT3 += 2.25
MDP 3 200 DAT3
T 1
MDP 6 1000 DAT622
MDP 6 1000 DAT621
MDP 8 1000 DAT820
T 3
MDP 6 1000 DAT623
MDP 6 1000 DAT622
MDP 8 1000 DAT826
MDP 6 1000 DAT900
MDP 6 1000 DAT904
MDP 8 1000 DAT900
MDP 8 1000 DAT904
DAT3 -= 2.25
"""
"-42" = """
MDP 3 200 DAT3
T 1
IF DAT1 != 6.75
DAT1 = 6.75
DAT1 -= 2
MDP 1 200 DAT1
DAT1 = 6.75
MDP 1 200 DAT1
ENDIF
DAT3 += 6.75
MDP 3 200 DAT3
T 1
MDP 6 1000 DAT622
MDP 6 1000 DAT621
MDP 8 1000 DAT820
T 3
MDP 6 1000 DAT623
MDP 6 1000 DAT622
MDP 8 1000 DAT826
MDP 6 1000 DAT900
MDP 6 1000 DAT904
MDP 8 1000 DAT900
MDP 8 1000 DAT904
DAT3 -= 6.75
"""
"-43" = """
MDP 3 200 DAT3
T 1
IF DAT1 != 11.25
DAT1 = 11.25
DAT1 -= 2
MDP 1 200 DAT1
DAT1 = 11.25
MDP 1 200 DAT1
ENDIF
DAT3 += 11.25
MDP 3 200 DAT3
T 1
MDP 6 1000 DAT622
MDP 6 1000 DAT621
MDP 8 1000 DAT820
T 3
MDP 6 1000 DAT623
MDP 6 1000 DAT622
MDP 8 1000 DAT826
MDP 6 1000 DAT900
MDP 6 1000 DAT904
MDP 8 1000 DAT900
MDP 8 1000 DAT904
DAT3 -= 11.25
"""
"-51" = """
MDP 3 200 DAT3
T 1
IF DAT1 != -6.75
DAT1 = -6.75
DAT1 -= 2
MDP 1 200 DAT1
DAT1 = -6.75
MDP 1 200 DAT1
ENDIF
DAT3 -= 6.75
MDP 3 200 DAT3
T 1
MDP 6 1000 DAT622
MDP 6 1000 DAT621
MDP 8 1000 DAT820
T 3
MDP 6 1000 DAT623
MDP 6 1000 DAT622
MDP 8 1000 DAT826
MDP 6 1000 DAT900
MDP 6 1000 DAT904
MDP 8 1000 DAT900
MDP 8 1000 DAT904
DAT3 += 6.75
"""
"-52" = """
MDP 3 200 DAT3
T 1
IF DAT1 != -11.25
DAT1 = -11.25
DAT1 -= 2
MDP 1 200 DAT1
DAT1 = -11.25
MDP 1 200 DAT1
ENDIF
DAT3 -= 11.25
MDP 3 200 DAT3
T 1
MDP 6 1000 DAT622
MDP 6 1000 DAT621
MDP 8 1000 DAT820
T 3
MDP 6 1000 DAT623
MDP 6 1000 DAT622
MDP 8 1000 DAT826
MDP 6 1000 DAT900
MDP 6 1000 DAT904
MDP 8 1000 DAT900
MDP 8 1000 DAT904
DAT3 += 11.25
"""
"-53" = """
MDP 3 200 DAT3
T 1
IF DAT1 != -15.75
DAT1 = -15.75
DAT1 -= 2
MDP 1 200 DAT1
DAT1 = -15.75
MDP 1 200 DAT1
ENDIF
DAT3 -= 15.75
MDP 3 200 DAT3
T 1
MDP 6 1000 DAT622
MDP 6 1000 DAT621
MDP 8 1000 DAT820
T 3
MDP 6 1000 DAT623
MDP 6 1000 DAT622
MDP 8 1000 DAT826
MDP 6 1000 DAT900
MDP 6 1000 DAT904
MDP 8 1000 DAT900
MDP 8 1000 DAT904
DAT3 += 15.75
"""
"-100" = """
MDP 3 200 DAT3
T 1
IF DAT1 != -2.25
DAT1 = -2.25
DAT1 -= 2
MDP 1 200 DAT1
DAT1 = -2.25
MDP 1 200 DAT1
ENDIF
MDP 8 1000 DAT822
MDP 8 1000 DAT821
MDP 6 1000 DAT620
T 3
MDP 8 1000 DAT823
MDP 8 1000 DAT822
MDP 6 1000 DAT626
MDP 8 1000 DAT900
MDP 8 1000 DAT904
MDP 6 1000 DAT900
MDP 6 1000 DAT904
"""
"-110" = """
MDP 3 200 DAT3
T 1
IF DAT1 != -2.25
DAT1 = -2.25
DAT1 -= 2
MDP 1 200 DAT1
DAT1 = -2.25
MDP 1 200 DAT1
ENDIF
DAT3 -= 2.25
MDP 3 200 DAT3
T 1
MDP 6 1000 DAT622
MDP 6 1000 DAT621
MDP 8 1000 DAT820
T 3
MDP 6 1000 DAT623
MDP 6 1000 DAT622
MDP 8 1000 DAT826
MDP 6 1000 DAT900
MDP 6 1000 DAT904
MDP 8 1000 DAT900
MDP 8 1000 DAT904
DAT3 += 2.25
"""
