# 将图片中的色码对应颜色转化为色码号
[sema]
"#000000" = 0
"#800000" = 1
"#008000" = 2
"#808000" = 3
"#000080" = 4
"#800080" = 5
"#C0DCC0" = 8
"#A6CAF0" = 9
"#DF0000" = 10
"#00BFBF" = 15
"#0000DF" = 16
"#9F9F00" = 17
"#DF9F00" = 21
"#00CD9F" = 22
"#9F00DF" = 23
"#BF9F00" = 31
"#00BF9F" = 32
"#9F00BF" = 33
"#E7C643" = 41
"#7281E4" = 42
"#9FDF00" = 43
"#BFDF00" = 51
"#00BFDF" = 52
"#DFBF00" = 53
"#863724" = 100
"#95A43E" = 110

[shaxian]
"#000000" = 1
"#800000" = 1
"#008000" = 2
"#808000" = 3
"#000080" = 4
"#800080" = 5
"#008080" = 6
"#C0C0C0" = 7
"#C0DCC0" = 8
"#A6CAF0" = 9
"#DF0000" = 10


[dumu]
"#000000" = 0
"#800000" = 1
"#008000" = 2
"#808000" = 3
"#000080" = 4
"#800080" = 5
"#008080" = 6
"#C0C0C0" = 7
"#C0DCC0" = 8
"#A6CAF0" = 9
"#DF0000" = 10



[luola]
"#000000" = 0
"#800000" = 1
"#008000" = 2
"#808000" = 3
"#000080" = 4
"#800080" = 5
"#008080" = 6
"#C0C0C0" = 7
"#C0DCC0" = 8
"#A6CAF0" = 9
"#DF0000" = 10