[dumu]
0 = """
DAT910 = 0
"""
1 = """
DAT910 = -1
"""
2 = """
DAT910 = -1.5
"""
3 = """
DAT910 = -2
"""
4 = """
DAT910 = -3
"""
5 = """
DAT910 = -4
"""
6 = """
DAT910 = -4.5
"""
7 = """
DAT910 = -5
"""
8 = """
DAT910 = -5.5
"""
9 = """
DAT910 = -6
"""
10 = """
DAT910 = -7
"""