[head_tail_cmd]
# 头部插入命令
head = """
MT 1 0 0
MT 2 0 0
MT 3 0 0
MT 5 0 0
MT 6 0 0
MT 8 0 0
ZERO 1 0
ZERO 2 0
ZERO 3 0
ZERO 4 0
ZERO 5 0
ZERO 6 0
ZERO 8 0
MDP 4 10 0
MTP 2 30000 30000 1000 65
MT 2 0 0
ZERO 2 0
POS_INIT 8 1000 -50 8.5 0.8 30
MDP 8 100  10
MDP 8 100  0
MDP 3 200 2.25
POS_INIT 6 1000 -50 8.5 0.8 30
MDP 6 100  10
MDP 6 100  0
MDP 3 200 0

DAT1 = 0
DAT2 = 0
DAT3 = 0
DAT5 = 0

DAT200 = 10
DAT201 = 20
DAT202 = 30
DAT300 = 0.4
DAT500 = 400
DAT501 = -100

DAT900 = 0
DAT901 = 30.5
DAT902 = 20.5
DAT903 = 11.7
DAT904 = 0.5

DAT620 = 11.5
DAT621 = 26.4
DAT622 = 38
DAT623 = 24.2
DAT626 = 20

DAT820 = 11.8
DAT821 = 26.9
DAT822 = 38.5
DAT823 = 24.5
DAT826 = 20.3

DAT910 = -6.5
DAT911 = 0
DAT912 = -1.5
DAT914 = -4
DAT915 = -6.5

DAT101 = 2.25
DAT102 = 4.50
DAT103 = 6.75
DAT104 = 9.00
DAT105 = 11.25
DAT106 = 13.50
DAT107 = 15.75
MS 5 50 50
DAT_INDEX = 0


DAT_YARN1 = 0
DAT_YARN2 = 0
DAT_YARN3 = 0
DAT_YARN4 = 0




DAT2_STA = 0
DAT2_END = 200
"""

# 尾部插入命令
tail = """
T 1000
"""