[line_switch]
# 正向换行组合
"+11" = """
DAT2 -= 4.3
DAT3 -= 4.3
"""
"+12" = """
DAT2 -= 4.3
DAT3 -= 4.3
"""
"+13" = """
DAT2 -= 4.3
DAT3 -= 4.3
"""
"+14" = """
DAT2 -= 4.3
DAT3 -= 4.3
"""
"+21" = """
DAT2 -= 4.3
DAT3 -= 4.3
"""
"+22" = """
DAT2 -= 4.3
DAT3 -= 4.3
"""
"+23" = """
DAT2 -= 4.3
DAT3 -= 4.3
"""
"+24" = """
DAT2 -= 4.3
DAT3 -= 4.3
"""
"+31" = """
DAT2 -= 4.3
DAT3 -= 4.3
"""
"+32" = """
DAT2 -= 4.3
DAT3 -= 4.3
"""
"+33" = """
DAT2 -= 4.3
DAT3 -= 4.3
"""
"+34" = """
DAT2 -= 4.3
DAT3 -= 4.3
"""
"+41" = """
DAT2 -= 4.3
DAT3 -= 4.3
"""
"+42" = """
DAT2 -= 4.3
DAT3 -= 4.3
"""
"+43" = """
DAT2 -= 4.3
DAT3 -= 4.3
"""
"+44" = """
DAT2 -= 4.3
DAT3 -= 4.3
"""

# 反向换行组合
"-11" = """
DAT2 += 4.3
DAT3 += 4.3
"""
"-12" = """
DAT2 += 4.3
DAT3 += 4.3
"""
"-13" = """
DAT2 += 4.3
DAT3 += 4.3
"""
"-14" = """
DAT2 += 4.3
DAT3 += 4.3
"""
"-21" = """
DAT2 += 4.3
DAT3 += 4.3
"""
"-22" = """
DAT2 += 4.3
DAT3 += 4.3
"""
"-23" = """
DAT2 += 4.3
DAT3 += 4.3
"""
"-24" = """
DAT2 += 4.3
DAT3 += 4.3
"""
"-31" = """
DAT2 += 4.3
DAT3 += 4.3
"""
"-32" = """
DAT2 += 4.3
DAT3 += 4.3
"""
"-33" = """
DAT2 += 4.3
DAT3 += 4.3
"""
"-34" = """
DAT2 += 4.3
DAT3 += 4.3
"""
"-41" = """
DAT2 += 4.3
DAT3 += 4.3
"""
"-42" = """
DAT2 += 4.3
DAT3 += 4.3
"""
"-43" = """
DAT2 += 4.3
DAT3 += 4.3
"""
"-44" = """
DAT2 += 4.3
DAT3 += 4.3
"""