# 后操作组合
[post_action]
"+00" = """
DAT_INDEX += 1
"""
"+01" = """
DAT_INDEX += 1
"""
"+10" = """
DAT_INDEX += 1
"""
"+11" = """
DAT_INDEX += 1
"""
"-00" = """
DAT_INDEX += 1
"""
"-01" = """
DAT_INDEX += 1
"""
"-10" = """
DAT_INDEX += 1
"""
"-11" = """
DAT_INDEX += 1
"""
