# 预操作组合
[pre_action]
"+00" = """
DAT2 += 4.5
DAT3 += 4.5
"""
"+01" = """
DAT2 += 2.25
DAT3 += 2.25
"""
"+10" = """
DAT2 += 6.75
DAT3 += 6.75
"""
"+11" = """
DAT2 += 4.5
DAT3 += 4.5
"""
"-00" = """
DAT2 -= 4.5
DAT3 -= 4.5
"""
"-01" = """
DAT2 -= 6.75
DAT3 -= 6.75
"""
"-10" = """
DAT2 -= 2.25
DAT3 -= 2.25
"""
"-11" = """
DAT2 -= 4.5
DAT3 -= 4.5
"""
