[shaxian_switch]
# 正向换纱线组合
"+12" = """
T 0
"""
"+13" = """
T 0
"""
"+14" = """
T 0
"""
"+21" = """
T 0
"""
"+23" = """
T 0
"""
"+24" = """
T 0
"""
"+31" = """
T 0
"""
"+32" = """
T 0
"""
"+34" = """
T 0
"""
"+41" = """
T 0
"""
"+42" = """
T 0
"""
"+43" = """
T 0
"""

# 反向换纱线组合
"-12" = """
T 0
"""
"-13" = """
T 0
"""
"-14" = """
T 0
"""
"-21" = """
T 0
"""
"-23" = """
T 0
"""
"-24" = """
T 0
"""
"-31" = """
T 0
"""
"-32" = """
T 0
"""
"-34" = """
T 0
"""
"-41" = """
T 0
"""
"-42" = """
T 0
"""
"-43" = """
T 0
"""