[shaxian_switch]
# 正向换纱线组合
"+12" = """
+12
"""
"+13" = """
+13
"""
"+14" = """
+14
"""
"+21" = """
+21
"""
"+23" = """
+23
"""
"+24" = """
+24
"""
"+31" = """
+31
"""
"+32" = """
+32
"""
"+34" = """
+34
"""
"+41" = """
+41
"""
"+42" = """
+42
"""
"+43" = """
+43
"""

# 反向换纱线组合
"-12" = """
-12
"""
"-13" = """
-13
"""
"-14" = """
-14
"""
"-21" = """
-21
"""
"-23" = """
-23
"""
"-24" = """
-24
"""
"-31" = """
-31
"""
"-32" = """
-32
"""
"-34" = """
-34
"""
"-41" = """
-41
"""
"-42" = """
-42
"""
"-43" = """
-43
"""