[line_sign]
1 = ["+","-"]
2 = ["+","+","-","-"]
3 = ["+","+","+","-","-","-"]
4 = ["+","+","+","+","-","-","-","-"]

# 每个动作的前后针板属性1是对前 0是对后
[zhenban_qianhou]
0 = 1
1 = 1
2 = 1
3 = 1
4 = 1
5 = 0
8 = 1
9 = 0
10 = 1
15 = 1
16 = 1
17 = 0
21 = 1
22 = 1
23 = 1
31 = 1
32 = 1
33 = 1
41 = 0
42 = 0
43 = 0
51 = 0
52 = 0
53 = 0
100 = 1
110 = 0